### ISSUE TITLE
Timezone issue

### ISSUE THREAD

**Issue by 1300371** [barasher/linky-to-influxdb#4]
Data are displayed with 2 hours shift ... 
I tried to play with timezone in query but nothing works ...
![influxdb](https://user-images.githubusercontent.com/32104009/61251187-02f4be80-a75a-11e9-9ad0-609f824143b8.png)

**Comment by barasher** [comment]
Outch, you're right :(
Influxdb is expecting a UTC timestamp and I provide it a "french time-zoned" timestamp.
I'll fix this this weekend and I'll have to figure it out why I don't have the same issue at home (I'm pretty sure that I dont provide any timezone in the query - I dont use tx('Europe/Paris')). 
I keep you in touch.

**Comment by 1300371** [comment]
Maybe you don't set the timezone in your container because I did.

**Comment by barasher** [comment]
I found the problem and fixed it. I just want to finalize some tests : it should be ok tomorrow.

**Comment by 1300371** [comment]
_* crossing fingers *_ 😄

**Comment by barasher** [comment]
Fixed on v1.1 (https://github.com/barasher/linky-to-influxdb/tree/v1.1).
Datetimes are now parsed using Europe/Paris timezone and pushed to InfluxDB as UTC (as required by Influxdb's lineprotocol).

I'll have to fix all the data that I've gathered at home, I'll share my correcting script (once written) if you need :)

Anyway, sorry for the inconvenience !

**Comment by 1300371** [comment]
No problem at all.  
Yep i will be interested in the fix script 👍

**Comment by barasher** [comment]
By the way, store your data using this new version in a new influxdb database. The script won't be able to distinguish wrong and right timezoned data.

**Comment by 1300371** [comment]
I can execute the script _before_ updating ...  so i'm still interested in
Btw i fork your project to inject your scripts into a container and execute it via Cron :)
Thx again for your work!

**Comment by barasher** [comment]
I don't know if you've noticed, but a Dockerfile is provided in the repository and I'm planning on releasing my Docker images on DockerHub. 
I already have some script that executes the Docker image using cron. I can provided them to you. Right now, you'll just have to build the Docker image yourself and you could use these scripts.

**Comment by 1300371** [comment]
Yep it's what i've already done: i adapt the dockerfile to my needs
I'm saying that i'm interested in your "correcting script" (to fix the existing influx db)

**Comment by barasher** [comment]
Here is the fix for already gathered data : https://github.com/barasher/linky-to-influxdb-tzfix
