### ISSUE TITLE
Date range

### ISSUE THREAD

**Issue by Darathor17** [barasher/linky-to-influxdb#5]
Hello Barasher!

Thank you very much for this work. I'm just wondering if it would be possible to select a date range to be able to load data for a month or year for instance (say at first to initialise InfluxDB)

thanks for your help!

Darathor

**Comment by barasher** [comment]
Hello,

Thank you :)

I've updated the "recover" utility, it now takes 2 arguments:
- the "starting date"
- the number of days to consider

So:
- if you want to recover only one day (01/12/2018 for instance), the arguments will be `01/12/2018 1`.
- if you want to recover data for 4 days from 01/12/2018, the arguments will be `01/12/2018 4`.

The documentation (README.MD) has been updated.

A new version, including this utility, has been released : v1.2. The corresponding docker image has also been pushed to DockerHub.

**Comment by barasher** [comment]
Tell me if everything's ok for you @Darathor17

**Comment by Darathor17** [comment]
Hello! Thank you for your reactiveness! I’ll test tonight or tomorrow 🙂

**Comment by Darathor17** [comment]
Just checked and it works very well! Thank you
